apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-mysql
  namespace: labwordpress
spec:
  selector:
    matchLabels:
      app: wp-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp-mysql
    spec:
      containers:
      - image: mysql:8.0.31
        name: wp-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_root_password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_password
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: wp-mysql
        volumeMounts:
        - name: mysql-persistent-storage-lab
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-lab
        persistentVolumeClaim:
          claimName: mysql-pvc