apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: labwordpress
  labels:
    app: wordpress
    tier: front
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: front
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress
        tier: front
    spec:
      containers:
        - image: wordpress:6.0.2
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wp-mysql
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
            - name: WORDPRESS_DB_NAME
              value: wordpress
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-persistent-storage-lab
      volumes:
        - name: wordpress-persistent-storage-lab
          persistentVolumeClaim:
            claimName: wordpress-pvc
  replicas: 1
