apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
  namespace: labwordpress
  labels:
    app: wp-mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: wp-mysql
