apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: labwordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 3308
      targetPort: 3308
  selector:
    app: wordpress
    tier: mysql
