apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: labwordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer
