apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: labwordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wordpress
    tier: front
  type: ClusterIP
