apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  namespace: labwordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: front
  type: LoadBalancer