apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: labwordpress
  labels:
    app: wordpress
spec:
  rules:
    - host: wordpress.compass.com
    - http:
        paths:
          - backend:
              service:
                name: wordpress-svc
                port:
                  number: 80
            pathType: Exact
